feat: upgrade to PostCSS 8
jonathantneal/postcss-media-fn pull request #2
Opened 2021-11-07 17:39 UTC by armano2

This PR upgrades the module to PostCSS 8 along with a few other changes:

- Upgraded ESLint to V7
- Upgraded postcss-tape to V6
- Change `postcss-value-parser` to `postcss-values-parser`
- Changed the engines since PostCSS supports only Node.js 10 and up
- Travis tests run on Node.js 10 and 12

see csstools/postcss-preset-env#191

2021-11-07 18:03 UTC, Antonio-Laguna requested changes
Hey @armano2!

Thanks a lot for the time you put into this PR and for getting this up to date with PostCSS 8! Really appreciate the fact you did create a GH Workflow to get this testable with GitHub actions.

I've taken a look and all seems sensible and I've just left some minor styling comments.

Nice work!

2021-11-07 18:03 UTC, Antonio-Laguna commented on README.md
> +npm install postcss postcss-media-fn --save-dev
I think this makes sense the way it was given it's consistent with the rest of the repos. See https://github.com/csstools/postcss-nesting  or https://github.com/csstools/postcss-advanced-variables

```suggestion
npm install postcss-media-fn --save-dev
```

2021-11-07 18:03 UTC, Antonio-Laguna commented on index.js
> +const postcss = require("postcss");
This should be single-quoted to be consistent.

```suggestion
const postcss = require('postcss');
```

2021-11-07 18:03 UTC, Antonio-Laguna commented on index.js
> +const {parse} = require('postcss-values-parser');
Let's also add spaces around here so it's consistent with the rest of the plugins.

```suggestion
const { parse } = require('postcss-values-parser');
```

2021-11-07 18:03 UTC, Antonio-Laguna commented on .github/workflows/ci.yaml
> +        node-version: [10.x, 12.x, 14.x, 16.x, 17.x]
Given we're not supporting 10.x with this change, I assume we should get rid of it.

2021-11-07 18:07 UTC, armano2 commented on .github/workflows/ci.yaml
> +        node-version: [10.x, 12.x, 14.x, 16.x, 17.x]
my mistake, i updated package.json to

```
  "engines": {
    "node": "^10 || ^12 || >=14"
  },
```

2021-11-07 18:08 UTC, armano2 commented on index.js
> +const {parse} = require('postcss-values-parser');
applied

2021-11-07 18:08 UTC, armano2 commented on index.js
> +const postcss = require("postcss");
applied

2021-11-07 18:10 UTC, armano2 commented
@Antonio-Laguna i applied those nits

2021-11-07 18:14 UTC, Antonio-Laguna commented on .github/workflows/ci.yaml
> +        node-version: [10.x, 12.x, 14.x, 16.x, 17.x]
Why not just `"node": ">=10"` ?

2021-11-07 18:28 UTC, armano2 commented on .github/workflows/ci.yaml
> +        node-version: [10.x, 12.x, 14.x, 16.x, 17.x]
node 11, and 13 is not supported

https://github.com/postcss/postcss/blob/7cccfac2a5d0b143186df86dd72591ec0ce6135b/package.json#L5-L7

2021-11-07 18:34 UTC, Antonio-Laguna commented on README.md
> +[css-url]: https://cssdb.org/#media-expressions
Given this is but an RFC these two links are 404ing. Could you get rid of these?

2021-11-08 06:40 UTC, Antonio-Laguna approved these changes

2021-11-08 06:40 UTC, Antonio-Laguna commented
Great work @armano2 !

2021-11-08 06:40 UTC, merged